name: GitHub Actions Build
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32c6
        path: ''
    - name: archive artifact
      run: |
        zip build/esp-coordinator-escp32-c6-usb-${{ github.tag }}.zip build/bootloader/bootloader.bin \
          build/esp-coordinator.bin build/ota_data_initial.bin partition_table/partition-table.bin
    - name: upload release artifact   
      uses: actions/upload-release-asset@v1
      with:
        path: build/esp-coordinator-escp32-c6-usb-${{ github.tag }}.zip
